### ISSUE TITLE
gitSavvy commit support

### ISSUE THREAD

**Issue by sheldon** [vovkkk/sublime_git_syntaxes#6]
Hey

Thanks for the awesome syntax pack.

I'm trying to get this syntax working with [gitsavvy](https://github.com/divmain/GitSavvy/issues/41), and struggling. I've configured their plugin to defer to sublime for commit syntax, but unless I manually set it when opening the window, it doesn't pick up your syntax. Any idea why this wouldn't work?

**Comment by vovkkk** [comment]
Gitsavvy supports only sublime-syntax definition https://github.com/divmain/GitSavvy/blob/0aff3d7c4f94039b841de32a6be18fd097f7b115/common/util/file.py#L24

But this package contains only tmLanguage definitions, because they are compatible with all versions of Sublime Text, while sublime-syntax is only for ST3.

You can create an event listener to apply syntax automatically, something like this (I did not test it, so it is more an idea than actual code):

```python
import sublime_plugin

class OverwriteGitsavvyCommitSyntax(sublime_plugin.EventListener):
    def on_post_text_command(view, command_name, args):
        if command_name != 'gs_commit_initialize_view':
            return
        view.set_syntax_file('Packages/GitSyntaxes/commit-message.tmLanguage')
```
And save this plugin as py file with any name in `Packages/User`.
